// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blogs: dynamic(() => import("./Blogs")),
  case_study: dynamic(() => import("./CaseStudy")),
  feature_job: dynamic(() => import("./FeatureJob")),
  navbar_data: dynamic(() => import("./NavbarData")),
  our_process: dynamic(() => import("./OurProcess")),
  section1: dynamic(() => import("./Section1")),
  services: dynamic(() => import("./Services")),
  testimonial: dynamic(() => import("./Testimonial")),
  trusted_type: dynamic(() => import("./TrustedType")),
  user_profile: dynamic(() => import("./UserProfile")),
};
